// lib/data/local/database.dart
//
// LOCAL DATABASE (Drift/SQLite)
// =============================
// This is the on-device database. All data is stored here first,
// then synced to Firestore when online.
//
// Drift is a type-safe SQLite wrapper for Dart. Instead of writing
// raw SQL strings, you write Dart code that generates SQL.
//
// KEY CONCEPTS:
// - @DriftDatabase = marks this as the main database class
// - @DataClass = generates a model class from a database table
// - MigrationStrategy = handles database schema changes over time
// - DAO = Data Access Object (queries for a specific table)

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'dart:io';

// This file is GENERATED by Drift. Run `dart run build_runner build` to generate it.
// We define the schema here and Drift generates the actual database code.
part 'database.g.dart';

// ──────────────────────────────────────────────
// TABLE DEFINITIONS
// ──────────────────────────────────────────────
// Each class = one database table.
// Each field = one column.

@DataClassName('LocalUser')
class Users extends Table {
  TextColumn get id => text();
  TextColumn get name => text();
  TextColumn get photoUrl => text().nullable();
  TextColumn get tradeTags => text().map(const ListConverter<String>());
  TextColumn get projectIds => text().map(const ListConverter<String>());
  DateTimeColumn get createdAt => dateTime();

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName('LocalProject')
class Projects extends Table {
  TextColumn get id => text();
  TextColumn get name => text();
  TextColumn get address => text().nullable();
  TextColumn get description => text().nullable();
  TextColumn get photoUrl => text().nullable();
  TextColumn get createdByUserId => text();
  IntColumn get status => intEnum<ProjectStatus>();
  DateTimeColumn get createdAt => dateTime();
  DateTimeColumn get completedAt => dateTime().nullable();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false));

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName('LocalProjectMembership')
class ProjectMemberships extends Table {
  IntColumn get id => integer().autoIncrement();
  TextColumn get userId => text();
  TextColumn get projectId => text();
  TextColumn get roles => text().map(const ListConverter<String>());
  DateTimeColumn get joinedAt => dateTime();
}

@DataClassName('LocalMeasurement')
class Measurements extends Table {
  TextColumn get id => text();
  TextColumn get projectId => text();
  TextColumn get measuredByUserId => text();
  RealColumn get length => real();
  RealColumn get width => real().nullable();
  RealColumn get height => real().nullable();
  IntColumn get unit => intEnum<MeasurementUnit>();
  TextColumn get materialType => text();
  IntColumn get quantity => integer().withDefault(const Constant(1));
  IntColumn get priority => intEnum<Priority>();
  TextColumn get notes => text().nullable();
  TextColumn get photoUrls => text().map(const ListConverter<String>());
  DateTimeColumn get createdAt => dateTime();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false));

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName('LocalCut')
class Cuts extends Table {
  TextColumn get id => text();
  TextColumn get measurementId => text();
  TextColumn get projectId => text();
  RealColumn get length => real();
  IntColumn get unit => intEnum<MeasurementUnit>();
  IntColumn get quantity => integer().withDefault(const Constant(1));
  IntColumn get status => intEnum<CutStatus>();
  TextColumn get cutByUserId => text().nullable();
  TextColumn get notes => text().nullable();
  TextColumn get flagReason => text().nullable();
  DateTimeColumn get createdAt => dateTime();
  DateTimeColumn get completedAt => dateTime().nullable();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false));

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName('LocalMaterial')
class Materials extends Table {
  TextColumn get id => text();
  TextColumn get projectId => text();
  TextColumn get name => text();
  TextColumn get typeCategory => text().nullable();
  TextColumn get size => text().nullable();
  IntColumn get quantityNeeded => integer();
  IntColumn get quantityOnSite => integer().withDefault(const Constant(0));
  RealColumn get unitCost => real().nullable();
  IntColumn get status => intEnum<MaterialStatus>();
  TextColumn get handledByUserId => text().nullable();
  TextColumn get supplier => text().nullable();
  TextColumn get notes => text().nullable();
  DateTimeColumn get createdAt => dateTime();
  DateTimeColumn get updatedAt => dateTime().nullable();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false));

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName('LocalCost')
class Costs extends Table {
  TextColumn get id => text();
  TextColumn get projectId => text();
  IntColumn get type => intEnum<CostType>();
  TextColumn get description => text();
  RealColumn get amount => real();
  TextColumn get addedByUserId => text();
  TextColumn get receiptUrl => text().nullable();
  DateTimeColumn get createdAt => dateTime();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false));

  @override
  Set<Column> get primaryKey => {id};
}

@DataClassName('LocalInstallation')
class Installations extends Table {
  TextColumn get id => text();
  TextColumn get projectId => text();
  TextColumn get description => text();
  TextColumn get locationOrArea => text().nullable();
  IntColumn get status => intEnum<InstallationStatus>();
  TextColumn get installedByUserId => text().nullable();
  TextColumn get notes => text().nullable();
  TextColumn get flagReason => text().nullable();
  TextColumn get photoUrls => text().map(const ListConverter<String>());
  DateTimeColumn get createdAt => dateTime();
  DateTimeColumn get completedAt => dateTime().nullable();
  DateTimeColumn get updatedAt => dateTime().nullable();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false));

  @override
  Set<Column> get primaryKey => {id};
}

// ──────────────────────────────────────────────
// LIST CONVERTER
// ──────────────────────────────────────────────
// SQLite doesn't have a "list" type, so we store lists as JSON strings
// and convert them back when reading.

class ListConverter<T> extends TypeConverter<List<T>, String> {
  const ListConverter();

  @override
  List<T> fromSql(String fromDb) {
    if (fromDb.isEmpty) return [];
    return (fromDb.split(',') as List).cast<T>();
  }

  @override
  String toSql(List<T> value) {
    return value.map((e) => e.toString()).join(',');
  }
}

// ──────────────────────────────────────────────
// DATABASE CLASS
// ──────────────────────────────────────────────

@DriftDatabase(tables: [
  Users,
  Projects,
  ProjectMemberships,
  Measurements,
  Cuts,
  Materials,
  Costs,
  Installations,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (Migrator m) async {
          await m.createAll();
        },
      );

  // ── User operations ──

  Future<void> insertUser(LocalUser user) => into(users).insert(user);
  Future<LocalUser?> getUser(String id) =>
      (select(users)..where((u) => u.id.equals(id))).getSingleOrNull();
  Future<List<LocalUser>> getAllUsers() => select(users).get();

  // ── Project operations ──

  Future<void> insertProject(LocalProject project) =>
      into(projects).insert(project);
  Future<LocalProject?> getProject(String id) =>
      (select(projects)..where((p) => p.id.equals(id))).getSingleOrNull();
  Future<List<LocalProject>> getAllProjects() => select(projects).get();
  Future<void> updateProject(LocalProject project) =>
      update(projects).replace(project);
  Future<void> deleteProject(String id) =>
      (delete(projects)..where((p) => p.id.equals(id))).go();

  // ── Measurement operations ──

  Future<void> insertMeasurement(LocalMeasurement m) =>
      into(measurements).insert(m);
  Future<List<LocalMeasurement>> getMeasurementsForProject(String projectId) =>
      (select(measurements)..where((m) => m.projectId.equals(projectId))).get();
  Future<void> deleteMeasurement(String id) =>
      (delete(measurements)..where((m) => m.id.equals(id))).go();

  // ── Cut operations ──

  Future<void> insertCut(LocalCut cut) => into(cuts).insert(cut);
  Future<List<LocalCut>> getCutsForProject(String projectId) =>
      (select(cuts)..where((c) => c.projectId.equals(projectId))).get();
  Future<void> updateCut(LocalCut cut) => update(cuts).replace(cut);

  // ── Material operations ──

  Future<void> insertMaterial(LocalMaterial material) =>
      into(materials).insert(material);
  Future<List<LocalMaterial>> getMaterialsForProject(String projectId) =>
      (select(materials)..where((m) => m.projectId.equals(projectId))).get();
  Future<void> updateMaterial(LocalMaterial material) =>
      update(materials).replace(material);

  // ── Cost operations ──

  Future<void> insertCost(LocalCost cost) => into(costs).insert(cost);
  Future<List<LocalCost>> getCostsForProject(String projectId) =>
      (select(costs)..where((c) => c.projectId.equals(projectId))).get();
  Future<void> updateCost(LocalCost cost) => update(costs).replace(cost);
  Future<void> deleteCost(String id) =>
      (delete(costs)..where((c) => c.id.equals(id))).go();

  // ── Installation operations ──

  Future<void> insertInstallation(LocalInstallation installation) =>
      into(installations).insert(installation);
  Future<List<LocalInstallation>> getInstallationsForProject(String projectId) =>
      (select(installations)..where((i) => i.projectId.equals(projectId))).get();
  Future<void> updateInstallation(LocalInstallation installation) =>
      update(installations).replace(installation);

  // ── Sync operations ──

  /// Get all unsynced records across all tables
  Future<List<LocalProject>> getUnsyncedProjects() =>
      (select(projects)..where((p) => p.isSynced.equals(false))).get();

  Future<List<LocalMeasurement>> getUnsyncedMeasurements() =>
      (select(measurements)..where((m) => m.isSynced.equals(false))).get();

  Future<List<LocalCut>> getUnsyncedCuts() =>
      (select(cuts)..where((c) => c.isSynced.equals(false))).get();

  Future<List<LocalMaterial>> getUnsyncedMaterials() =>
      (select(materials)..where((m) => m.isSynced.equals(false))).get();

  Future<List<LocalCost>> getUnsyncedCosts() =>
      (select(costs)..where((c) => c.isSynced.equals(false))).get();

  Future<List<LocalInstallation>> getUnsyncedInstallations() =>
      (select(installations)..where((i) => i.isSynced.equals(false))).get();
}

// ──────────────────────────────────────────────
// DATABASE CONNECTION
// ──────────────────────────────────────────────
// Opens (or creates) the SQLite database file on the device.

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    // Get the app's documents directory
    final dbFolder = await getApplicationDocumentsDirectory();
    // Create the database file
    final file = File(p.join(dbFolder.path, 'constructflow.db'));
    return NativeDatabase.createInBackground(file);
  });
}
